### ISSUE TITLE
Problem when updating opam

### ISSUE THREAD

**Issue by fblanqui** [coq-contribs/aac-tactics#1]
[ERROR] At ~/.opam/repo/coq-released/packages/coq-aac-tactics/coq-aac-tactics.8.5.0/opam:14:45:
  Not a recognised version-control URL
[ERROR] At ~/.opam/repo/coq-released/packages/coq-aac-tactics/coq-aac-tactics.8.5.1/opam:14:45:
  Not a recognised version-control URL

**Comment by matej-kosik** [comment]
Hi. I have tried to reproduce the problem, like this:

```bash
$ opam repo list
  30 [http]  coq-released     https://coq.inria.fr/opam/released
  20 [http]     default     https://opam.ocaml.org

$ opam install -v -j4 coq
$ opam install -v coq-aac-tactics.8.5.0
$ opam upgrade
```

but failed. For me, the above commands worked fine. So I am not sure what is wrong.

If you can, please post the output of the following commands:
```bash
$ opam repo list
$ cat ~/.opam/repo/coq-released/packages/coq-aac-tactics/coq-aac-tactics.8.5.0/opam
$ cat ~/.opam/repo/coq-released/packages/coq-aac-tactics/coq-aac-tactics.8.5.1/opam
```

**Comment by silene** [comment]
You should use `opam lint` to detect this kind of problems:

    $ cd released/packages/coq-aac-tactics/coq-aac-tactics.8.5.1/
    $ opam lint
    [ERROR] At .../released/packages/coq-aac-tactics/coq-aac-tactics.8.5.1/opam:14:45:
      Not a recognised version-control URL
    File format error

(opam 1.2.0)

**Comment by matej-kosik** [comment]
The errors you guys mention are produced by `opam` installed as a Debian package, or by something you compiled yourselves?

In my context:
- when I use opam 1.2 compiled from source, everything is fine (`opam lint` prints `PASSES`)
- when I use opam 1.3 compiled from source, everything is fine (`opam lint` print `PASSES`)
- when I use opam from `master` branch, I get a similar error that I can fix by replacing `https` by `git+https`.

That, however, does not fix your problem. When I try to use `opam` provided as a Debian package, I still get an error.

At the moment I am not sure what is the right thing to do.

**Comment by matej-kosik** [comment]
Ok. I think I've figured out what to do. I've pushed appropriate commit (https://github.com/coq/opam-coq-archive/commit/ab6abd2b4cc6fc9bb63ece421c08d338d3688eb7)

Let me please know if everything works on your side.

Thank you.

**Comment by silene** [comment]
It is easy to fix, just use the actual address of the repository rather than using a webpage: `https://github.com/coq-contribs/aac-tactics.git`. `opam` is actually right to complain since there is no way it can use the address currently in the `opam` file to perform a checkout.

**Comment by matej-kosik** [comment]
Thanks. Done (https://github.com/coq/opam-coq-archive/commit/408c36d627369bc1ea67af28baf5c05286906057).
