### ISSUE TITLE
Please tag a version for Coq 8.6

### ISSUE THREAD

**Issue by gares** [coq-contribs/aac-tactics#3]
Debian uses this repository as the upstream of AAC tactics.
To switch to Coq 8.6 we'd like to have a tag for AAC tactic pointing to a commit that compiles with 8.6.

**Comment by matej-kosik** [comment]
Good idea.

I've added a new tag `v8.6.0` which marks a commit of `aac-tactics` that was (last time we checked) compilable with Coq 8.6.
